import { useWebsite } from "../hooks/useWebsite";
import { Link } from "react-router-dom";
import PageFx from "../components/ui/PageFx";
import Icon from "../components/ui/Icon";
import HopeSculpture from "../components/motion/HopeSculpture";
import ReelsCarousel from "../components/ui/ReelsCarousel";
import instagram from "../data/instagram-reels.json";
import { useMotion } from "../hooks/useMotion";

function Asterisk({ className = "" }) {
  return <svg className={className} viewBox="0 0 100 100" fill="none" aria-hidden="true"><path d="M50 0v100M0 50h100M15 15l70 70m0-70L15 85" stroke="currentColor" strokeWidth="16" /></svg>;
}

export default function Home() {
  const { field: cms } = useWebsite();
  const PROGRAMS = [
    { number: "01", title: cms("home.programs.title-a-little-of-you-a-life-for-someone"), category: cms("home.programs.category-blood-donation"), image: cms("home.programs.image-images-together-webp"), alt: cms("home.programs.alt-moonlit-volunteers-at-a-blood-donation-ce"), to: "/programs#blood", icon: "droplet", description: cms("home.programs.description-connecting-willing-donors-with-th") },
    { number: "02", title: cms("home.programs.title-for-a-greener-kinder-tomorrow"), category: cms("home.programs.category-environment"), image: cms("home.programs.image-images-community-webp"), alt: cms("home.programs.alt-moonlit-volunteers-cleaning-kozhikode-bea"), to: "/programs#environment", icon: "leaf", description: cms("home.programs.description-cleaner-shores-more-trees-a-share") },
    { number: "03", title: cms("home.programs.title-young-people-limitless-potential"), category: cms("home.programs.category-youth-development"), image: cms("home.programs.image-images-volunteers-webp"), alt: cms("home.programs.alt-the-moonlit-volunteer-community-gathered-"), to: "/programs#youth", icon: "sun", description: cms("home.programs.description-turning-curiosity-and-compassion-") },
  ];
const STATS = [{ count: cms("home.stats.count-2000"), label: cms("home.stats.label-volunteers-one-purpose"), note: cms("home.stats.note-a-community-that-shows-up") }, { count: cms("home.stats.count-1000"), label: cms("home.stats.label-families-supported"), note: cms("home.stats.note-care-that-reaches-further") }, { count: cms("home.stats.count-30"), label: cms("home.stats.label-communities-reached"), note: cms("home.stats.note-change-close-to-home") }, { count: cms("home.stats.count-120"), label: cms("home.stats.label-relief-campaigns"), note: cms("home.stats.note-together-when-it-matters") }];

  const { enabled, reduced, toggle } = useMotion();
  return <PageFx className="home-page">
    <section className="home-hero site-container" aria-labelledby="hero-title">
      <div className="hero-copy">
        <p className="section-label hero-reveal"><span className="live-dot" />{" "}{cms("home.hero.young-minds-shared-purpose")}</p>
        <h1 id="hero-title"><span className="hero-line"><span>{cms("home.hero.small-acts")}</span></span><span className="hero-line"><span>{cms("home.hero.extraordinary")}</span></span><span className="hero-line hero-line--accent"><span>{cms("home.hero.change")}<span className="hero-period">.</span><svg viewBox="0 0 480 24" preserveAspectRatio="none" aria-hidden="true"><path d="M3 17C108 2 318 0 475 13M35 23C173 12 316 10 449 19" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" /></svg></span></span></h1>
        <p className="hero-description hero-reveal">{cms("home.hero.we-re-a-youth-led-movement-turning-compassion")}</p>
        <div className="hero-actions hero-reveal"><Link className="action-button action-button--blue" data-magnetic to="/get-involved#volunteer">{cms("home.hero.find-your-purpose")}{" "}<span className="button-circle"><Icon size={18} /></span></Link><Link className="text-link" to="/about">{cms("home.hero.meet-moonlit")}{" "}<Icon name="arrow-right" size={18} /></Link></div>
        <div className="hero-proof hero-reveal"><div className="proof-portraits" aria-hidden="true"><img src={cms("home.hero.image-images-together-webp")} alt="" /><img src={cms("home.hero.image-images-volunteers-webp")} alt="" /><img src={cms("home.hero.image-images-community-webp")} alt="" /><span>+</span></div><p><strong>{cms("home.hero.2-000-changemakers")}</strong><span>{cms("home.hero.there-s-a-place-here-for-you")}</span></p></div>
      </div>
      <div className="hero-art" aria-label="Our volunteers creating change in Kerala">
        <div className="hero-orbit" aria-hidden="true" />
        <div className="hero-photo-wrap hero-reveal" data-parallax="-25"><img className="hero-photo" src={cms("home.hero.image-images-community-webp-2")} alt={cms("home.hero.image-description-two-moonlit-volunteers-coll")} width="1400" height="1867" fetchPriority="high" /><div className="photo-caption"><span className="live-dot" />{" "}{cms("home.hero.on-the-ground-making-a-difference")}</div></div>
        <div className="hero-sculpture hero-reveal"><HopeSculpture /><span>{cms("home.hero.a-little-good")}<br /><strong>{cms("home.hero.endless-possibility")}</strong></span></div>
        <Link className="hero-community-card hero-reveal" to="/gallery" data-tilt><img src={cms("home.hero.image-images-volunteers-webp-2")} alt={cms("home.hero.image-description-our-beach-cleanup-volunteer")} width="1000" height="750" /><div><span>{cms("home.hero.good-people")}<br /><strong>{cms("home.hero.great-things")}</strong></span><span className="round-arrow"><Icon size={18} /></span></div></Link>
        <div className="hero-seal hero-reveal" aria-hidden="true"><svg viewBox="0 0 120 120" className="seal-text" data-spin><defs><path id="seal-circle" d="M60,60 m-44,0 a44,44 0 1,1 88,0 a44,44 0 1,1 -88,0" /></defs><text><textPath href="#seal-circle" textLength="275">TRAVEL · VOLUNTEER · TRANSFORM · </textPath></text></svg><Icon name="heart" size={33} /></div>
        <span className="hero-coordinate">{cms("home.hero.11-2588-n-75-7804-e")}<br />{cms("home.hero.rooted-in-kerala-india")}</span>
      </div>
      <div className="hero-bottom"><a href="#our-impact" className="scroll-cue"><span><Icon name="arrow-down" size={16} /></span>{cms("home.hero.scroll-to-feel-the-difference")}</a><button className="motion-toggle" onClick={toggle} disabled={reduced} aria-pressed={enabled} aria-label={reduced ? "Motion disabled by your system preference" : enabled ? "Pause animations" : "Enable animations"}><Icon name={enabled ? "pause" : "play"} size={13} />{reduced ? "Reduced motion" : `Motion ${enabled ? "on" : "off"}`}</button><span className="hero-founded">{cms("home.hero.a-youth-led-nonprofit-since-2021")}</span></div>
    </section>

    <div className="purpose-marquee" aria-label="Travel with purpose. Volunteer with heart. Grow together."><div className="marquee-track" aria-hidden="true">{[0, 1, 2, 3].map((i) => <div className="marquee-set" key={i}><span>{cms("home.page-content.travel-with-purpose")}</span><Asterisk /><span className="marquee-outline">{cms("home.page-content.volunteer-with-heart")}</span><Asterisk /><span>{cms("home.page-content.grow-together")}</span><Asterisk /></div>)}</div></div>

    <section className="impact-section site-container" id="our-impact" tabIndex={-1} aria-labelledby="impact-title"><div className="impact-intro mf-fade"><p className="section-label">{cms("home.our-impact.the-difference-we-make")}</p><h2 id="impact-title">{cms("home.our-impact.small-beginnings")}<br /><span className="serif-word">{cms("home.our-impact.real-impact")}</span></h2><p>{cms("home.our-impact.behind-every-number-a-human-story")}</p></div><div className="impact-grid">{STATS.map((stat) => <div className="impact-stat mf-fade" key={stat.label}><strong><span data-count={stat.count} data-suffix="+">{stat.count.toLocaleString("en-IN")}+</span></strong><h3>{stat.label}</h3><p>{stat.note}</p></div>)}</div></section>

    <section className="story-section site-container" aria-labelledby="story-title">
      <div className="story-visual mf-fade"><div className="story-photo"><img src={cms("home.story.image-images-volunteers-webp")} alt={cms("home.story.image-description-moonlit-s-project-sulaimani")} width="1000" height="750" loading="lazy" data-parallax="30" /></div><div className="story-note"><Asterisk /><p>{cms("home.story.a-shared-purpose")}<br />{cms("home.story.a-thousand-possibilities")}</p></div><a href={cms("home.story.link-https-www-instagram-com-reel-dxtm9gmd8yb")} className="story-watch" target="_blank" rel="noopener noreferrer"><span><Icon name="play" size={17} /></span>{cms("home.story.life-at-moonlit")}{" "}<Icon size={15} /></a></div>
      <div className="story-copy mf-fade"><p className="section-label"><span className="tiny-star">✳</span>{" "}{cms("home.story.this-is-moonlit")}</p><h2 id="story-title">{cms("home.story.big-hearts")}<br />{cms("home.story.bigger")}{" "}<span className="serif-word">{cms("home.story.possibilities")}</span></h2><p className="story-lead">{cms("home.story.we-believe-the-world-changes-when-ordinary-pe")}</p><p>{cms("home.story.born-in-kerala-in-2021-moonlit-brings-young-p")}</p><Link className="text-link" to="/about">{cms("home.story.the-story-behind-the-movement")}{" "}<span className="round-arrow"><Icon size={18} /></span></Link><div className="story-values"><span><Icon name="heart" size={16} />{" "}{cms("home.story.people-first")}</span><span><Icon name="globe" size={16} />{" "}{cms("home.story.purpose-always")}</span><span><Icon name="sun" size={16} />{" "}{cms("home.story.youth-powered")}</span></div></div>
    </section>

    <section className="programs-section" aria-labelledby="programs-title"><div className="site-container">
      <div className="section-heading mf-fade"><div><p className="section-label">{cms("home.programs.many-ways-to-make-a-difference")}</p><h2 id="programs-title">{cms("home.programs.good-comes-in")}<br /><span className="serif-word">{cms("home.programs.many-forms")}</span></h2></div><div><p>{cms("home.programs.find-the-cause-that-moves-you")}<br />{cms("home.programs.we-ll-find-a-way-to-move-it-forward-together")}</p><Link className="text-link" to="/programs">{cms("home.programs.explore-our-work")}{" "}<Icon name="arrow-right" size={18} /></Link></div></div>
      <div className="home-program-grid">{PROGRAMS.map((program) => <Link to={program.to} key={program.category} className="home-program-card mf-fade" data-tilt><div className="program-image"><img src={program.image} alt={program.alt} loading="lazy" width="600" height="650" /><span className="program-category"><Icon name={program.icon} size={15} />{program.category}</span><span className="program-number">/{program.number}</span><h3>{program.title}</h3><span className="program-link-arrow"><Icon size={23} /></span></div><p>{program.description}</p></Link>)}</div>
      <div className="more-programs mf-fade"><span>{cms("home.programs.and-wherever-else-we-re-needed")}</span><Link to="/programs#welfare"><Icon name="people" size={20} />{cms("home.programs.community-welfare")}{" "}<Icon size={18} /></Link><Link to="/programs#relief"><Icon name="heart" size={20} />{cms("home.programs.disaster-relief")}{" "}<Icon size={18} /></Link></div>
    </div></section>

    <section className="belong-section site-container" aria-labelledby="belong-title"><div className="belong-panel">
      <div className="belong-copy mf-fade"><p className="section-label">{cms("home.belong.not-just-volunteering-belonging")}</p><h2 id="belong-title">{cms("home.belong.find-your-people")}<br />{cms("home.belong.find-your")}{" "}<span className="serif-word">{cms("home.belong.purpose")}</span></h2><p>{cms("home.belong.new-places-lasting-friendships-a-chance-to-do")}</p><Link className="action-button action-button--yellow" to="/get-involved#volunteer" data-magnetic>{cms("home.belong.come-be-part-of-it")}{" "}<span className="button-circle"><Icon size={18} /></span></Link><Link className="belong-events" to="/events">{cms("home.belong.see-upcoming-experiences")}{" "}<Icon name="arrow-right" size={17} /></Link></div>
      <div className="belong-art" aria-hidden="true"><div className="orbit-ring orbit-ring--one" /><div className="orbit-ring orbit-ring--two" /><div className="orbit-ring orbit-ring--three" /><Asterisk className="belong-star" /><div className="belong-polaroid belong-polaroid--one" data-parallax="-35"><img src={cms("home.belong.image-images-volunteers-webp")} alt="" loading="lazy" /><span>{cms("home.belong.strangers-our-people")}</span></div><div className="belong-polaroid belong-polaroid--two" data-parallax="25"><img src={cms("home.belong.image-images-together-webp")} alt="" loading="lazy" /><span>{cms("home.belong.a-little-time-a-lot-of-heart")}</span></div><span className="belong-tag">{cms("home.belong.your-people-are-here")}</span></div>
    </div></section>

    <section className="journal-section site-container" aria-labelledby="journal-title"><div className="section-heading mf-fade"><div><p className="section-label">{cms("home.journal.postcards-from-the-ground")}</p><h2 id="journal-title">{cms("home.journal.the-good")}{" "}<span className="serif-word">{cms("home.journal.in-motion")}</span></h2></div><a href={cms("home.journal.link-https-www-instagram-com-moonlit-foundati")} target="_blank" rel="noopener noreferrer" className="text-link"><Icon name="instagram" size={18} />{cms("home.journal.moonlit-foundation")}{" "}<Icon size={16} /></a></div><div className="journal-grid">
      <a className="journal-card mf-fade" href={cms("home.journal.link-https-www-instagram-com-reel-dxtm9gmd8yb")} target="_blank" rel="noopener noreferrer"><div className="journal-image"><img src={cms("home.journal.image-images-community-webp")} alt={cms("home.journal.image-description-volunteers-making-kozhikode")} loading="lazy" width="800" height="600" /><span className="journal-play"><Icon name="play" size={20} /></span><span className="journal-location"><Icon name="pin" size={13} />{cms("home.journal.kozhikode-kerala")}</span></div><div className="journal-meta"><span>{cms("home.journal.environment")}</span><span>{cms("home.journal.project-sulaimani")}</span></div><h3>{cms("home.journal.one-beach-many-hands")}<br />{cms("home.journal.a-cleaner-tomorrow")}<Icon size={25} /></h3></a>
      <a className="journal-card mf-fade" href={cms("home.journal.link-https-www-instagram-com-reel-dxjxmsek-tn")} target="_blank" rel="noopener noreferrer"><div className="journal-image"><img src={cms("home.journal.image-images-volunteers-webp")} alt={cms("home.journal.image-description-young-volunteers-coming-tog")} loading="lazy" width="1000" height="750" /><span className="journal-play"><Icon name="play" size={20} /></span><span className="journal-location"><Icon name="pin" size={13} />{cms("home.journal.kozhikode-kerala-2")}</span></div><div className="journal-meta"><span>{cms("home.journal.our-community")}</span><span>{cms("home.journal.better-together")}</span></div><h3>{cms("home.journal.show-up-for-a-cause")}<br />{cms("home.journal.leave-with-a-community")}<Icon size={25} /></h3></a>
    </div></section>

    <section id="instagram-reels" className="instagram-section site-container" aria-labelledby="instagram-title">
      <div className="section-heading mf-fade"><div><p className="section-label">{cms("home.instagram-reels.real-people-real-moments")}</p><h2 id="instagram-title">{cms("home.instagram-reels.a-little-closer-to")}{" "}<span className="serif-word">{cms("home.instagram-reels.the-action")}</span></h2></div><a className="text-link" href={instagram.profileUrl} target="_blank" rel="noopener noreferrer"><Icon name="instagram" size={18} />@{instagram.account}<Icon size={16} /></a></div>
      <ReelsCarousel items={instagram.reels} account={instagram.account} />
    </section>

    <section className="home-final-cta"><div className="site-container mf-fade"><p className="section-label">{cms("home.home-final-cta.the-next-good-thing-starts-with-you")}</p><h2>{cms("home.home-final-cta.be-someone-s")}<br /><span className="serif-word">{cms("home.home-final-cta.reason-to-hope")}</span><Asterisk /></h2><div className="final-cta-bottom"><p>{cms("home.home-final-cta.your-time-your-kindness-your-support")}<br />{cms("home.home-final-cta.it-all-makes-a-difference")}</p><Link className="action-button action-button--blue" to="/get-involved" data-magnetic>{cms("home.home-final-cta.let-s-make-a-difference")}{" "}<span className="button-circle"><Icon size={19} /></span></Link></div></div></section>
  </PageFx>;
}
